services:
  mkdoc:
    image: squidfunk/mkdocs-material:9
    restart: always
    container_name: sofia-app-docs
    hostname: sofia.app.docs.com
    volumes:
      - ./config/:/docs 
    networks:
      - docs
    ports:
      - "8030:8000"

networks:
  docs:
    driver: bridge